services:
#########################
# TAILSCALE | Secure Remote Access
#########################
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    restart: unless-stopped

    hostname: poppi
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    env_file:
      - .env    
    secrets:
      - TS_AUTHKEY
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      # - TS_AUTHKEY=${TS_AUTHKEY:?err}
      - TS_USERSPACE=false
      # - TS_ACCEPT_DNS=${TS_ACCEPT_DNS} # Désactive le DNS de Tailscale (AdGuard gère ça)
      # - TS_EXTRA_ARGS=${TS_EXTRA_ARGS}
    volumes:
      - ${DATA:?err}/tailscale/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    security_opt:
      - no-new-privileges:true

secrets:
  TS_AUTHKEY:
    file: ./.secrets