services:
  ##########################
  ## DOCKGE | Dashboard
  ##########################
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    env_file:
      - '/home/basic/Homelab/compose/compose.env'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKGE_STACKS_DIR=/opt/stacks
    cap_drop:
      - ALL
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ../compose:/opt/stacks
    networks:
      - frontend_net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
networks:
  frontend_net:
    driver: bridge
    external: true
