services:
  #########################
  # DOCKGE | Manage Containers
  #########################
  dockge:
    image: louislam/dockge:1.4.2
    container_name: dockge
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5001:5001
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - DOCKGE_STACKS_DIR=${STACKS:?err}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA:?err}/dockge/data:/app/data
      - ${STACKS:?err}:${STACKS:?err}:ro
    networks:
      - frontend
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
networks:
  frontend:
    driver: bridge
    external: true
