services:
  ##########################
  ## HOMEPAGE | Dashboard
  ##########################
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.6
    container_name: homepage
    restart: unless-stopped
    ports:
      - 3001:3001
    env_file:
      - .env
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TZ:?err}
      - HOMEPAGE_ALLOWED_HOSTS=localhost:3001,127.0.0.1:3001,${HOSTNAME:?err}:3001 # Authorize
    volumes:
      - ${DATA:?err}/homepage/config:/app/config
      - ${DATA:?err}/homepage/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - frontend
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s      
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'

networks:
  frontend:
    name: frontend
    driver: bridge
