services:
  ##########################
  ## HOMEPAGE | Dashboard
  ##########################
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TZ:?err}
      - HOMEPAGE_ALLOWED_HOSTS=localhost:3000,poppi:3000 # Authorize
    volumes:
      - ${DATA:?err}/homepage/config:/app/config
      - ${DATA:?err}/homepage/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - frontend
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
networks:
  frontend:
    driver: bridge
    external: true
