services:
#########################
# VAULTWARDEN | keychain
#########################
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    
    env_file:
      - ${BASE_DIR}/.env
    environment:
      - TZ=${TZ}
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
    volumes:
      - ./data:/data
    networks:
      - frontend_net
    ports:
      - "8080:80"    
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  frontend_net:
    driver: bridge
    external: true