services:
  #########################
  # VAULTWARDEN | keychain
  #########################
  vaultwarden:
    image: vaultwarden/server:1.32.3
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - "8080:80"    
    env_file:
      - .env
    secrets:
      - ADMIN_TOKEN 
    environment:
      - DOMAIN=https://vault.tondomaine.com     
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      # - ADMIN_TOKEN=${ADMIN_TOKEN:?err}
    volumes:
      - ${DATA:?err}/vaultwarden/data:/data
    networks:
      - frontend
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5' 

secrets:
  ADMIN_TOKEN:
    file: ./.secrets

networks:
  frontend:
    name: frontend
    driver: bridge
