services:
  #########################
  # VAULTWARDEN | keychain
  #########################
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    env_file:
      - .env
    secrets:
      - ADMIN_TOKEN 
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      # - ADMIN_TOKEN=${ADMIN_TOKEN:?err}
    volumes:
      - ${DATA}/vaultwarden/data:/data
    networks:
      - frontend
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '0.5' 

secrets:
  ADMIN_TOKEN:
    file: ./.secrets

networks:
  frontend:
    driver: bridge
    external: true
