services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${DATA}/ollama/data:/root/.ollama
    networks:
      - ai
    security_opt:
      - no-new-privileges:true

networks:
  ai:
    driver: bridge
    external: true