include:
  - ./traefik/compose.yml
  - ./crowdsec/compose.yml
  - ./authentik/compose.yml

  - ./jellyfin/compose.yml
  - ./immich/compose.yml
  - ./nextcloud/compose.yml

  - ./ollama/compose.yml
  - ./open-webui/compose.yml

  - ./watchtower/compose.yml