# docker network create frontend
# docker network create backend
# docker network create downloads
# docker network create ai

networks:
  frontend:
    name: frontend
    driver: bridge
    external: true

  backend:
    name: backend
    driver: bridge

  downloads:
    name: downloads
    driver: bridge
    external: true

  ai:
    name: ai
    driver: bridge
    external: true    