services:

  db:
    image: IMAGE:TAG
    container_name: DB_NAME
    restart: unless-stopped

    env_file:
      - ${BASE_DIR}/.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./db:/var/lib/postgresql/data

    networks:
      - backend_net
    security_opt:
      - no-new-privileges:true
   # cap_drop:
   #    - ALL  # Deactivate ALL default capabilities
   #  cap_add:
   #    - NET_ADMIN  # Manage network interface
   #    - NET_RAW    # Manage RAW packages (necessary for Tailscale)    
    # deploy:
    #   resources:
    #     limits:
    #       memory:
    #       cpus:   
    # depends_on:
    #   - 
    # healthcheck:

networks:
  # Database  
  backend_net:
    driver: bridge
    external: true