services:
########################
# APP | Use
#########################
  app:
    image: 
    container_name:
    # network-mode: service:
    env_file:
      - .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - ./data:/data

    networks:
      - 
    ports:
      -       
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
  
    # depends_on:
    #   - 
    # deploy:
    #   resources:
    #     limits:
    #       memory:
    #       cpus: 

networks:
  frontend_net:
    external: true
