services:
########################
# APP | Use
#########################
  app:
    image: 
    container_name:
    # network-mode: service:
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/app:/app/config
      - ${DATA_ROOT}/app:/app/data

    # depends_on:
    #   - 
    networks:
      - 
    ports:
      - 
    # deploy:
    #   resources:
    #     limits:
    #       memory:
    #       cpus: 
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  ${networks_net}:
    external: true