services:
########################
# APP | Use
#########################
  app:
    image: IMAGE:TAG
    container_name: NAME
    restart: unless-stopped    
    # network-mode: service:NAME
    
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - NAME_PASSWORD=${NAME_PASSWORD}
      - NAME_API_KEY=${NAME_API_KEY}
      - NAME_TOKEN=${NAME_TOKEN}
    ports:
      - "HOST_PORT:CONTAINER_PORT" #HTTP/HTTPS/WEBUI
    volumes:
      - ./config:/config
      - ./data:/data
      - ${MEDIA_DIR}:/media:ro
      - ${DOWNLOAD_DIR}:/downloads
      
    networks:
      - network_name    
    security_opt:
      - no-new-privileges:true
   # cap_drop:
   #    - ALL  # Deactivate ALL default capabilities
   #  cap_add:
   #    - NET_ADMIN  # Manage network interface
   #    - NET_RAW    # Manage RAW packages (necessary for Tailscale)    
    # deploy:
    #   resources:
    #     limits:
    #       memory:
    #       cpus:   
    # depends_on:
    #   - 
    # healthcheck:
    
networks:
  # Exposed Services
  frontend_net:
    driver: bridge
    external: true
  # Database  
  backend_net:
    driver: bridge
    external: true
  # Torrent
  download_net:
    driver: bridge
    external: true
