services:
########################
# CADDY | Reverse Proxy
#########################
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
  
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
      - ./config:/config
    networks:
      - frontend_net
    security_opt:
      - no-new-privileges:true

networks:
  frontend_net:
    external: true
