services:
########################
# ADGUARDHOME | Home DNS
#########################
  adguardhome:
    image:  adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    networks:
      - frontend_net
    ports:
      - 53:53/tcp # plain dns over tcp
      - 53:53/udp # plain dns over udp
      - 82:82/tcp # http web interface
      - 3000:3000/tcp # initial setup web interface
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    security_opt:
      - no-new-privileges:true

networks:
  frontend_net:
    external: true
